atp_django/atp/urls.py
from django.urls import path
from . import views, forms

app_name = "atp"
urlpatterns = [
    # ex: /atp/
    path("", views.IndexView.as_view(), name="index"),
    path("request/", views.UserFormView.as_view(), name="request"),
    path("request/money", views.MoneyView.as_view(), name="money"),
]

atp_django/atp_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('atp/', include("atp.urls")),
    path('admin/', admin.site.urls),
]

atp_django/atp/models.py
from django.db import models


class Transaction(models.Model):
    amount = models.IntegerField(default=0)
    aux_money = models.IntegerField(default=0)
    status = models.CharField(max_length=100, default="On going")
    message = models.CharField(max_length=100, default="Transacción en proceso")

    def __str__(self):
        return str(self.pk)

        
class Bills(models.Model):
    quantity: int = models.IntegerField()
    value: int = models.SmallIntegerField()
    img = models.CharField(max_length=100, default="atp/images/cajero.gif")

    def __str__(self):
        return str(self.value)

atp_django/atp/forms.py
from django import forms
from django.db import models
from .models import Bills, Transaction

class NumberForm(forms.Form):
    digital_number = forms.IntegerField()

    def __str__(self):
        return str(self.digital_number)

atp_django/atp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest, HttpResponseNotFound, HttpResponseRedirect
from django.views import generic
from django.views.generic import View

import math

from .forms import NumberForm
from .models import Bills, Transaction



class IndexView(generic.ListView):
    template_name: str = 'atp/index.html'
    context_object_name = 'transaction'

    def get_queryset(self):
        """
        Escribe la cantidad de dinero de la transacción que está en proceso,
        o escribe cero para que una nueva transacción sea ejecutada
        """
        n = []
        total_t = Transaction.objects.all()
        for i in total_t:
            n.append(i.pk)
        t_id = max(n)
        if Transaction.objects.get(pk=t_id).status == "On going":
            transaction = Transaction.objects.get(pk=t_id)
        else:
            transaction = Transaction()
            transaction.save()

        return transaction


class UserFormView(generic.ListView):
    model = Transaction
    form_class = NumberForm
    template_name: str = 'atp/request.html'

    def post(self, request):
        if request.method == 'POST':
            form = self.form_class(request.POST)            
            if form.is_valid():
                n = []
                total_t = Transaction.objects.all()
                for i in total_t:
                    n.append(i.pk)
                t = Transaction.objects.get(pk=max(n))
                t.amount = form.cleaned_data['digital_number']
                t.save()
                return render(request, 'atp/request.html', {'form': form})
        else:
            form = self.form_class()

        return render(request, 'atp/request.html', {'form': form})

    def get(self, request):
        if request.method == 'GET':
            form = self.form_class(request.GET)
            if form.is_valid():
                n = []
                total_t = Transaction.objects.all()
                for i in total_t:
                    n.append(i.pk)
                t = Transaction.objects.get(pk=max(n))
                t.amount = form.cleaned_data['digital_number']
                t.save()
                return render(request, 'atp/request.html', {'form': form})
        else:
            form = self.form_class()

        return render(request, 'atp/request.html', {'form': form})

        

class MoneyView(generic.ListView):
    model = Transaction
    form_class = NumberForm
    template_name: str = 'atp/money.html'


    def post(self, request):
        if request.method == 'POST':
            form = self.form_class(request.POST)
            if form.is_valid():
                n = []
                total_t = Transaction.objects.all()
                for i in total_t:
                    n.append(i.pk)
                transaction = Transaction.objects.get(pk=max(n))
                
                transaction.requested_bills = []
                box = Bills.objects.all()
                transaction.aux_money = int(form.cleaned_data['digital_number'])
                papers = 0

                for bi in box[::-1]:
                    if transaction.aux_money > 0:
                        div = math.floor(transaction.aux_money / bi.value)
                        if div > bi.quantity:
                            papers = bi.quantity
                        else:
                            papers = div
                        
                        bill = Bills()
                        bill.quantity = papers
                        bill.value = bi.value
                        bill.img = f"atp/images/{bill.value}.jpg"
                        transaction.requested_bills.append(bill)

                        transaction.aux_money -= bi.value * papers
                        if transaction.aux_money > 0:
                            pass
                        else:
                            bi.quantity -= papers

                if transaction.aux_money == 0:
                    transaction.message = "The transaction was done correctly"
                    transaction.status = "Finished"
                    transaction.save()
                else:
                    transaction.message = "Soy un cajero malo, he sido malo y no puedo darte esa cantidad"
                    transaction.status = "Failed"
                    transaction.save()

                return render(request, 'atp/money.html', {'transaction': transaction})
        else:
            form = self.form_class()

        return render(request, 'atp/money.html', {'form': form})

    def get(self, request):
        if request.method == 'GET':
            form = self.form_class(request.GET)
            if form.is_valid():
                n = []
                total_t = Transaction.objects.all()
                for i in total_t:
                    n.append(i.pk)
                transaction = Transaction.objects.get(pk=max(n))
                transaction.status = "Finished"
                transaction.message = "The transaction was done correctly"
                transaction.save()
                return render(request, 'atp/money.html', {'transaction': transaction})
        else:
            form = self.form_class()

        return render(request, 'atp/money.html', {'form': form})
        
        
        

atp_django/atp/templates/atp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'atp/reset.css' %}">
    <link rel="stylesheet" href="{% static 'atp/style.css' %}">
    <title>Index</title>
</head>
<body>
    <header class="header">
        <span class="tagline">ATP Django</span>
    </header>
    <main class="container">
        <section class="section-user-display">
            <div class="money-tag">
                <p>Introduce la cantidad de dinero deseada:</p>
                <br>
                <span>$</span><span id="digital_number" name="digital_number">{{ transaction.amount }}</span>
                <br>
                <span hidden>Status: </span><span hidden>{{ transaction.status }}</span>
                <br>
            </div>
            <figure class="atp-image">
                <img src="{% static 'atp/images/lector-tarjetas.png' %}">
            </figure>
        </section>
        <section class="section-forms">
            <form class="atp-buttons" id="atp-numbers">
                <input type="button" value="1" name="number-1" id="number-1">
                <input type="button" value="2" name="number-2" id="number-2">
                <input type="button" value="3" name="number-3" id="number-3">
                <br>
                <input type="button" value="4" name="number-4" id="number-4">
                <input type="button" value="5" name="number-5" id="number-5">
                <input type="button" value="6" name="number-6" id="number-6">
                <br>
                <input type="button" value="7" name="number-7" id="number-7">
                <input type="button" value="8" name="number-8" id="number-8">
                <input type="button" value="9" name="number-9" id="number-9">
                <br>
                <input type="button" value="0" name="number-0" id="number-0">
            </form>
            <form action="{% url 'atp:request' %}" method='POST' class="atp-buttons" id="atp-delete-submit">
                {% csrf_token %}
                <input type="number" name="digital_number" id="number_box" value="{{ transaction.amount }}" hidden>
                <input type="button" value="Borrar" id="delete" name="delete">
                <input type="submit" value="Solicitar" id="submit" name="submit">
            </form>
        </section>
    </main>
    <footer class="footer">
        <span>AndresFlamel</span>
        <span>andres.sanchez.cloud@gmail.com</span>
        <span>AndresStark</span>
    </footer>
    <script src="{% static 'atp/index.js' %}"></script>
</body>
</html>

atp_django/atp/templates/atp/money.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'atp/reset.css' %}">
    <link rel="stylesheet" href="{% static 'atp/money.css' %}">
    <title>Money</title>
</head>
<body>
    <header>
        {% if transaction.aux_money == 0 %}
        <span class="header-span-title">Transacción Exitosa</span><br><br>
        <span class="header-span-textnumber">Cantidad extraída: </span>
        <span class="header-span-number">${{ transaction.amount }}</span>
        {% else %}
        <span class="header-span-title">Transacción Fallida</span><br><br>
        <span class="header-span-title">Soy un cajero malo, he sido malo y no puedo darte esa cantidad</span><br><br>
        {% comment %} <span class="header-span-title">No hay suficiente dinero en la caja</span><br><br> {% endcomment %}
        {% endif %}
    </header>
    <main>
        <section class="main-section-input">
            <form action="{% url 'atp:index' %}" class="section-form-return">
                <input type="submit" value="Nueva Transacción" class="form-input-return">
            </form>
        </section>
        {% if transaction.aux_money == 0 %}
        <section class="main-section-img">
            <figure>
                {% for img in transaction.requested_bills %}
                    {% if img.quantity > 0 %}
                        {% with ''|center:img.quantity as range %}
                            {% for _ in range %}
                                <img src="{% static img.img %}">
                            {% endfor %}
                        {% endwith %}
                    {% endif %}
                {% endfor %}
            </figure>
        </section>
        {% endif %}
    </main>
</body>
</html>

atp_django/atp/templates/atp/request.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'atp/reset.css' %}">
    <link rel="stylesheet" href="{% static 'atp/requests.css' %}">
    <title>Request</title>
</head>
<body>
    <header>
        {% if form.cleaned_data.digital_number == 0 %}
        <span class="header-span-text">Transacción fallida</span>
        {% else %}
        <span class="header-span-text">Se extraerá:</span><br>
        <span class="header-span-number">${{ form.cleaned_data.digital_number }}</span>
        {% endif %}
    </header>
    <main>
        <section>
            {% if form.cleaned_data.digital_number == 0 %}
            <form action="{% url 'atp:index' %}" class="section-form-return">
                <input type="submit" value="Regresar" class="form-input-return">
            </form>
            {% else %}
            <form action="{% url 'atp:index' %}" class="section-form-return">
                <input type="submit" value="Regresar" class="form-input-return">
            </form>
            <form action="{% url 'atp:money' %}" method='POST' class="section-form-confirm">
                {% csrf_token %}
                <input type="number" name="digital_number"  value="{{ form.cleaned_data.digital_number }}" hidden>
                <input type="submit" value="Confirmar" class="form-input-confirm">
            </form>
            {% endif %}
        </section>
    </main>
</body>
</html>